// Code generated by yo. DO NOT EDIT.

{{if .BuildTag -}}
// +build {{ .BuildTag}}
{{- end -}}

// Package {{ .Package.Name }} contains the types.
package {{ .Package.Name }}

import (
{{- range .PackageRegistry.GetImports }}
	{{ . }}
{{- end }}
)
