// Code generated by yo. DO NOT EDIT.

{{if .BuildTag -}}
// +build {{ .BuildTag}}
{{- end -}}

// Package {{ .Package }} contains the types.
package {{ .Package }}

import (
	"context"
	"errors"
	"fmt"

	"cloud.google.com/go/spanner"
	"google.golang.org/api/iterator"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)
